- hosts: all
  remote_user: root
  roles:
    - common
    
- hosts: rstudio
  remote_user: root
  roles:
    - r_latest
    - rstudio

- hosts: gitlab_runners
  remote_user: root
  roles:
    - docker
    - gitlab_runner

- hosts: docker
  remote_user: root
  roles:
    - docker

- hosts: r
  remote_user: root
  roles:
    - emacs
    - docker
    - r-base
    - r

- hosts: scala
  remote_user: root
  roles:
    - emacs
    - docker
    - r-base
    - scala

#- hosts: communications
#  remote_user: root
#  vars:
#    traefik_dir: /var/www/traefik
#    acme_email: acme_prl@o1o.ch
#  roles:
#    - docker
#    - traefik
#    - mattermost
#    - watchtower
#    - simple_monitoring
