---
- name: Create the watchtower container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    restart_policy: unless-stopped
    pull: true
    recreate: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
