---
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "root"
    group: "docker"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    mode: 0600

- name: Adding traefik.yml file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_dir }}/traefik.yml"
    mode: 0600

- name: traefik netowrk
  community.general.docker_network:
    name: traefik

- name: Create the traefik container
  community.general.docker_compose:
    project_name: traefik
    pull: true
    definition:
      version: '3.3'
      networks:
        traefik:
          external:
            name: traefik
      services:
        traefik:
          networks:
            - traefik
          container_name: traefik
          restart: unless-stopped
          image: traefik:v2.4
          ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:8080:8080"
          volumes:
            - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
            - "{{ traefik_dir }}/acme.json:/acme.json"
            - /var/run/docker.sock:/var/run/docker.sock:ro
